import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await b.newContext({ viewport: { width: 1440, height: 950 } });
const p = await ctx.newPage();
p.on('console', (m) => { if (m.type()==='error') console.log('CONSOLE', m.text().slice(0,120)); });
await p.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await p.getByRole('button', { name: 'Edit a copy of this page' }).click();
await p.waitForURL(/\/studio\//);
await p.waitForTimeout(2000);
const names = await p.locator('[data-pocket]').evaluateAll((els) => els.map((e) => e.getAttribute('aria-label')));
console.log('pockets:', names);
const a = p.getByRole('button', { name: /^Pocket row 3, column 1/ });
const c = p.getByRole('button', { name: /^Pocket row 3, column 2/ });
const ba = await a.boundingBox(); const bc = await c.boundingBox();
console.log('boxes', !!ba, !!bc);
await p.mouse.move(ba.x + ba.width/2, ba.y + ba.height/2);
await p.mouse.down();
await p.mouse.move(bc.x + bc.width/2, bc.y + bc.height/2, { steps: 10 });
await p.mouse.up();
await p.waitForTimeout(400);
const pressed = await p.locator('[data-pocket][aria-pressed="true"]').evaluateAll((els)=>els.map(e=>e.getAttribute('data-pocket')));
console.log('selected after drag:', pressed);
console.log('prompt:', await p.locator('.gb-prompt').first().innerText());
await b.close();
